# Generated by Django 5.2.14 on 2026-06-30 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('html_content', models.TextField(blank=True)),
                ('status_code', models.IntegerField(default=200)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etag', models.CharField(blank=True, max_length=256)),
                ('content_type', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawledLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2048)),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='src.crawledpage')),
            ],
            options={
                'unique_together': {('source_page', 'target_url')},
            },
        ),
    ]
