# Generated by Django 5.2.14 on 2026-06-30 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_crawledpage_crawledlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
