# Generated by Django 5.2.14 on 2026-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_questionbank_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperquestion',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
