# Generated by Django 5.2.14 on 2026-06-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_paperquestion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
